### ISSUE TITLE
Feat: Add Folder Watching

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#20]
**Describe the bug**
The application does not show any music in a created directory

**To Reproduce**
1. Create an empty folder
2. Add the folder to svunes
3. Add music to the folder
4. No are music shown

**Expected behavior**
A reload button for the folder or watch for change in the folder

**Screenshots**

**System information (please complete the following information):**
 - OS version: Windows 11 23h2 build 22631.3880
 - Version rc-1.0.0

**Additional information**
Add any other information about the problem here.

**Comment by Tormak9970** [comment]
I didn't even think of that, great idea. Will work on adding that

**Comment by Tormak9970** [comment]
Added with https://github.com/Tormak9970/Svunes/commit/eafd6b497b48e063c178dc4c723b406a5107fd44
