### ISSUE TITLE
feat: Add speaker selector

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#21]
**Describe the feature you'd like**.
Add a speaker selector to choose where the audio is output.

**Please provide context on why you'd like this**
Like many people, I listen to music in my headphones, but sometimes I like to listen on an external speaker that isn't linked to my PC (Bluetooth devices), it would be nice to have a built-in audio selector so I don't have to change all the PC settings.

**Comment by Tormak9970** [comment]
I'll look into this. May require redoing how audio is currently played
