### ISSUE TITLE
Bug: Application crash due to file name

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#23]
**Describe the bug**
After adding new music to the folder, the application crashes. 

**To Reproduce**
1. Go to your music folder
2. Add a music named like this: `KDA - POPSTARS (ft. Madison Beer, (G)I-DLE, Jaira Burns)`
3. Open the application

**Expected behavior**
- No error
- Be more explicit in case of error

**Screenshots**
![image](https://github.com/user-attachments/assets/6c2f3061-9be0-496a-8ca8-80e3cca2d69b)

**System information (please complete the following information):**
 - OS version: Windows 11
 - Version rc-1.0.0

**Additional information**
Add any other information about the problem here.

**Comment by Tormak9970** [comment]
@Sukaato it can't be more explicit in this case because that's a fallback for the catch-all case. Rust currently does not allow you to get the error message in that scenario (which is dumb).

This is probably due to there being a `.` in the file name. Should be an easy fix

**Comment by Sukaato** [comment]
I have other song with a `.`, i think its due to the `()` char

**Comment by Tormak9970** [comment]
That's also a likely culprit

**Comment by Sukaato** [comment]
after a little check, its the only song with comma in it i have

**Comment by Tormak9970** [comment]
fixed with changes to filename parsing
