### ISSUE TITLE
Bug No music is played

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#24]
**Describe the bug**
Clicking on a song does not play it

**To Reproduce**
1. Go to artists
2. Select one of it
3. Click on a song
4. Music does not start

**Expected behavior**
Listen to the music

**Screenshots**
![image](https://github.com/user-attachments/assets/7ce2ffbb-b4c1-40c9-a619-3de859abf95a)

**System information (please complete the following information):**
 - OS version: [e.g. iOS 17, Android 14, Windows 10, Arch KDE]
 - Version [e.g. v1.0.0]

**Additional information**
Even clicking on the play button does nothing

**Comment by Tormak9970** [comment]
@Sukaato Can you test if that song is playable on the Songs and Albums view? Playing songs on the Artists page seems to work for me

**Comment by Sukaato** [comment]
I go on every views, no one play the music

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Svunes/commit/79181e64ad725709d6d2d3f555d6c2acf34be9d0
