### ISSUE TITLE
Feat: Add a balance for L/R

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#29]
**Describe the feature you'd like**
Add a balance to configure L/R output

**Please provide context on why you'd like this**
As a person with fewer ears on the right, but who loves music, I like to hear the same volume in both ears. It might be interesting to configure a balance so that, instead of 50% left and 50% right, you get 40% left and 60% right, or whatever you like.

**Comment by Tormak9970** [comment]
I've added L/R channel balancing with https://github.com/Tormak9970/Svunes/commit/1e8c136e6506846099c89db4b30d4b78e149c271
