### ISSUE TITLE
Bug: Can see dropdown on song wiew

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#31]
**Describe the bug**
Can see all item of the dropdown in detail song view

**To Reproduce**
1. Click on the song displayed in bottom left
2. Click on edit icon on upper right
3. See you does not see all options

**Expected behavior**
See all options

**Screenshots**
![image](https://github.com/user-attachments/assets/729d6180-4986-4159-bdc0-dec7de9468cb)

**System information (please complete the following information):**
 - OS version: Windows 11
 - Version v1.0.0-rc

**Additional information**
Add any other information about the problem here.

**Comment by Tormak9970** [comment]
fixed in https://github.com/Tormak9970/Svunes/commit/5f5796766a129ca1b5956126ae9e3edffc4d66c8
