### ISSUE TITLE
Feat: Adapt volume icon

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#32]
**Describe the feature you'd like**
Like youtube player, adapte the volume icon 

- VolumeOff: 0%
- VolumeDown: 1% to 50%
- VolumeUp: 51% to 100%

**Please provide context on why you'd like this**
for a11y and rapid visual check of volume

**Comment by Tormak9970** [comment]
Probably a good idea given that on desktop you can't immediately see the volume level
