### ISSUE TITLE
Bug: app not listed in windows volume mixer

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#33]
**Describe the bug**
Svunes does not appear in `Windows > Sound > Volume Mixer`

**To Reproduce**
1. Open Windows Settings
2. Click on `system` > `sound`
4. Scroll down to `Volume mixer`
5. Svunes is not shown

**Expected behavior**
See svunes on mixer.

**Screenshots**
![image](https://github.com/user-attachments/assets/04c875cb-2945-4b93-b12a-28da5e193bd2)

**System information (please complete the following information):**
 - OS version: Windows 11
 - Version v1.0.0-rc

**Additional information**
may be linked to: 
- #21 
- #24

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Svunes/commit/79181e64ad725709d6d2d3f555d6c2acf34be9d0
