### ISSUE TITLE
Bug: thumbnail not displayed

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#34]
**Describe the bug**
All of my thumbnail album are not displayed on song of the album

**To Reproduce**
1. Add a music that have a thumbnail
2. No thumbnail

**Expected behavior**
Have a beautiful thumbnail

**Screenshots**
![image](https://github.com/user-attachments/assets/fb7730eb-4ce9-4c61-a7a5-dff5edbfe24d)
![image](https://github.com/user-attachments/assets/092e420f-767b-45d3-8195-817edcc2b829)

**System information (please complete the following information):**
 - OS version: Windows
 - Version v1.0.0-rc

**Additional information**
Add any other information about the problem here.

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Svunes/commit/9b08344d263b01dd6ee32c1baa781a5eb5efaf11
