### ISSUE TITLE
bug: multiple popover can existe has the same time

### ISSUE THREAD

**Issue by Sukaato** [Tormak9970/Svunes#41]
**Describe the bug**
Multiple popover can exist at the same time

**To Reproduce**
1. Click on volume
2. Click on speaker selector
3. Volume popover is not closed

**Expected behavior**
Allow only one popover to exist at the same time
+ Click outside the popover should be close the popover too.

**Screenshots**
![image](https://github.com/user-attachments/assets/f528312c-bc1a-43d6-9a5a-ec8108c11efc)

**System information (please complete the following information):**
 - OS version: Windows 11

**Additional information**
Add any other information about the problem here.

**Comment by Tormak9970** [comment]
fixed with https://github.com/Tormak9970/Svunes/commit/3cb6c5abbb17dbfe98adb2a36f7806bf0bf0fa1c
